version: "3.8"

services:
  fmask_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    image: fmask-pipeline:latest
    container_name: fmask-pipeline-cmd
    restart: unless-stopped
    privileged: true
    cpus: 4.0
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/kedro_docker/key.json
      - OPENBLAS_NUM_THREADS=16
      - OMP_NUM_THREADS=16
      - MKL_NUM_THREADS=16
    volumes:
      - ${PWD}/conf/local:/home/kedro_docker/conf/local
      - ${PWD}/data:/home/kedro_docker/data
      - ${PWD}/logs:/home/kedro_docker/logs
      - ${PWD}/notebooks:/home/kedro_docker/notebooks
      - ${PWD}/references:/home/kedro_docker/references
      - ${PWD}/results:/home/kedro_docker/results
      - ./key.json:/home/kedro_docker/key.json
    command: kedro run --pipeline=coastline_cfmask_landsat_deepwatermap
